spring:
  profiles:
    include:
    - "default"

logging:
  level:
    org.springframework: "INFO"
    net.playground.casclient: "DEBUG"

server:
  port: 9000

management:
  endpoint:
    logfile:
      external-file: "logs/application.log"